# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Faculta/AN2/Sem 2/AC/ProiectFinalMipsPipeline/ProiectFinalMipsPipeline.cache/wt} [current_project]
set_property parent.project_path {D:/Faculta/AN2/Sem 2/AC/ProiectFinalMipsPipeline/ProiectFinalMipsPipeline.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Faculta/AN2/Sem 2/AC/ProiectFinalMipsPipeline/ProiectFinalMipsPipeline.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/IDecode.vhd}
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/MainControl.vhd}
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/SSD.vhd}
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/IFetch.vhd}
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/MEM.vhd}
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/MPG.vhd}
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/ExecutionUnit.vhd}
  {D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/sources_1/imports/Desktop/lab7_4.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/constrs_1/imports/Desktop/Basys3_test_env.xdc}}
set_property used_in_implementation false [get_files {{D:/Faculta/AN2/Sem 2/AC/MipsPipeline/project_profu.srcs/constrs_1/imports/Desktop/Basys3_test_env.xdc}}]


synth_design -top lab7_4 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab7_4.dcp

catch { report_utilization -file lab7_4_utilization_synth.rpt -pb lab7_4_utilization_synth.pb }
